version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
  
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "monthly"
