services:
  - type: web
    name: portfolio-website
    runtime: static
    buildCommand: make deploy
    staticPublishPath: ./output
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: BRIDGETOWN_ENV
        value: production
    domains:
      - oscarbarlow.com
