services:
  - type: web
    name: portfolio-website
    runtime: static
    buildCommand: make
    staticPublishPath: ./output
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
      - ./output
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: BRIDGETOWN_ENV
        value: production
    domains:
      - oscarbarlow.com
