services:
  - type: web
    name: portfolio-website
    runtime: static
    buildCommand: make
    staticPublishPath: ./output
    pullRequestPreviewsEnabled: true
    envVars:
      - key: BRIDGETOWN_ENV
        value: production
    domains:
      - oscarbarlow.com
