services:
  - type: web
    name: portfolio-website
    runtime: static
    region: frankfurt
    buildCommand: make
    staticPublishPath: ./output
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
      - ./output
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true