name: PR CI

on:
  pull_request:
  push:
    paths:
      - "*"
    branches:
      - "*"
      - "!master"

jobs:
  pr-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          - node-version: 20
      - name: Checkout code
        uses: actions/checkout@v4

      - name: spellcheck
        run: |
          yarn && make spellcheck
