name: Spellcheck

permissions:
  checks: write

on:
  pull_request:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: spellcheck
        run: |
          yarn && make spellcheck

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: failure()
        with:
          report_paths: '**/spag.junit.xml'
