name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn test:run

    - name: Run spellcheck
      run: make spellcheck

    - name: Upload test coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage/lcov.info
        flags: javascript
        name: JavaScript Coverage
        fail_ci_if_error: false